# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!

# Imports modules from the GUI toolkit PyQt
from PyQt5 import QtCore, QtGui, QtWidgets

import os
from serial.tools import list_ports
from pyqtgraph import PlotWidget

from core.printer import console_control

# The main window that provides the framework for building oppscan.py's user interface
class Ui_MainWindow(object):
    
    # Builds UI for oppscan.py
    def setupUi(self, MainWindow):
        """Sets up the user interface for the main window of the application.

        Args:
            MainWindow (object): should store the main window object.
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1275, 901)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsCap = PlotWidget(self.centralwidget)
        self.graphicsCap.setGeometry(QtCore.QRect(380, 70, 481, 221))
        self.graphicsCap.setObjectName("graphicsCap")
        self.labelCap = QtWidgets.QLabel(self.centralwidget)
        self.labelCap.setGeometry(QtCore.QRect(380, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelCap.setFont(font)
        self.labelCap.setObjectName("labelCap")
        self.conThread_stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.conThread_stop_btn.setGeometry(QtCore.QRect(480, 300, 91, 23))
        self.conThread_stop_btn.setObjectName("conThread_stop_btn")
        self.prt_send_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.prt_send_txt.setGeometry(QtCore.QRect(20, 250, 211, 21))
        self.prt_send_txt.setObjectName("prt_send_txt")
        self.prt_send_txt.setEnabled(False)
        self.prt_send_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_send_btn.setGeometry(QtCore.QRect(230, 249, 111, 23))
        self.prt_send_btn.setObjectName("prt_send_btn")
        self.prt_send_btn.setEnabled(False)
        self.prt_x_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.prt_x_lcd.setGeometry(QtCore.QRect(30, 115, 64, 23))
        self.prt_x_lcd.setObjectName("prt_x_lcd")
        self.prt_y_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.prt_y_lcd.setGeometry(QtCore.QRect(120, 115, 64, 23))
        self.prt_y_lcd.setObjectName("prt_y_lcd")
        self.prt_z_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.prt_z_lcd.setGeometry(QtCore.QRect(210, 115, 64, 23))
        self.prt_z_lcd.setObjectName("prt_z_lcd")
        self.labelCap_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelCap_3.setGeometry(QtCore.QRect(20, 115, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCap_3.setFont(font)
        self.labelCap_3.setObjectName("labelCap_3")
        self.labelCap_4 = QtWidgets.QLabel(self.centralwidget)
        self.labelCap_4.setGeometry(QtCore.QRect(110, 115, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCap_4.setFont(font)
        self.labelCap_4.setObjectName("labelCap_4")
        self.labelCap_5 = QtWidgets.QLabel(self.centralwidget)
        self.labelCap_5.setGeometry(QtCore.QRect(200, 115, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCap_5.setFont(font)
        self.labelCap_5.setObjectName("labelCap_5")
        self.prt_yp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_yp_btn.setGeometry(QtCore.QRect(79, 140, 21, 21))
        
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prt_yp_btn.setFont(font)
        self.prt_yp_btn.setObjectName("prt_yp_btn")
        self.prt_yp_btn.setEnabled(False)
        self.prt_xp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_xp_btn.setGeometry(QtCore.QRect(129, 180, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prt_xp_btn.setFont(font)
        self.prt_xp_btn.setObjectName("prt_xp_btn")
        self.prt_xp_btn.setEnabled(False)
        self.prt_zp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_zp_btn.setGeometry(QtCore.QRect(217, 140, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prt_zp_btn.setFont(font)
        self.prt_zp_btn.setObjectName("prt_zp_btn")
        self.prt_zp_btn.setEnabled(False)
        self.prt_yn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_yn_btn.setGeometry(QtCore.QRect(79, 220, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prt_yn_btn.setFont(font)
        self.prt_yn_btn.setObjectName("prt_yn_btn")
        self.prt_yn_btn.setEnabled(False)
        self.prt_xn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_xn_btn.setGeometry(QtCore.QRect(29, 180, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prt_xn_btn.setFont(font)
        self.prt_xn_btn.setObjectName("prt_xn_btn")
        self.prt_xn_btn.setEnabled(False)
        self.prt_zn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_zn_btn.setGeometry(QtCore.QRect(217, 220, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prt_zn_btn.setFont(font)
        self.prt_zn_btn.setObjectName("prt_zn_btn")
        self.prt_zn_btn.setEnabled(False)
        self.con_connect_bt = QtWidgets.QPushButton(self.centralwidget)
        self.con_connect_bt.setGeometry(QtCore.QRect(380, 40, 61, 23))
        self.con_connect_bt.setObjectName("con_connect_bt")
        self.con_com_sel = QtWidgets.QComboBox(self.centralwidget)
        self.con_com_sel.setGeometry(QtCore.QRect(590, 40, 52, 22))
        self.con_com_sel.setEditable(True)
        self.con_com_sel.setObjectName("con_com_sel")
        for _ in list_ports.comports():
            self.con_com_sel.addItem("")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(560, 40, 21, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(650, 41, 31, 20))
        self.label_2.setObjectName("label_2")
        self.con_baud_sel = QtWidgets.QComboBox(self.centralwidget)
        self.con_baud_sel.setEnabled(True)
        self.con_baud_sel.setGeometry(QtCore.QRect(680, 40, 52, 22))
        self.con_baud_sel.setEditable(True)
        self.con_baud_sel.setObjectName("con_baud_sel")
        self.con_baud_sel.addItem("")
        self.con_baud_sel.addItem("")
        self.conThread_start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.conThread_start_btn.setGeometry(QtCore.QRect(380, 300, 91, 23))
        self.conThread_start_btn.setObjectName("conThread_start_btn")
        self.con_refreshrate_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.con_refreshrate_lcd.setGeometry(QtCore.QRect(797, 41, 64, 23))
        palette = QtGui.QPalette()
        self.con_refreshrate_lcd.setPalette(palette)
        self.con_refreshrate_lcd.setStyleSheet("")
        self.con_refreshrate_lcd.setObjectName("con_refreshrate_lcd")
        self.labelCap_8 = QtWidgets.QLabel(self.centralwidget)
        self.labelCap_8.setGeometry(QtCore.QRect(20, 0, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelCap_8.setFont(font)
        self.labelCap_8.setObjectName("labelCap_8")
        self.prt_home_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_home_btn.setGeometry(QtCore.QRect(20, 60, 141, 23))
        self.prt_home_btn.setObjectName("prt_home_btn")
        self.prt_home_btn.setEnabled(False)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 30, 21, 20))
        self.label_3.setObjectName("label_3")
        self.prt_com_sel = QtWidgets.QComboBox(self.centralwidget)
        self.prt_com_sel.setGeometry(QtCore.QRect(200, 30, 52, 22))
        self.prt_com_sel.setEditable(True)
        self.prt_com_sel.setObjectName("prt_com_sel")
        for _ in list_ports.comports():
            self.prt_com_sel.addItem("")
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 30, 31, 20))
        self.label_4.setObjectName("label_4")
        self.prt_baud_sel = QtWidgets.QComboBox(self.centralwidget)
        self.prt_baud_sel.setEnabled(True)
        self.prt_baud_sel.setGeometry(QtCore.QRect(290, 30, 52, 22))
        self.prt_baud_sel.setEditable(True)
        self.prt_baud_sel.setObjectName("prt_baud_sel")
        self.prt_baud_sel.addItem("")
        self.prt_baud_sel.addItem("")
        self.homelabel = QtWidgets.QLabel(self.centralwidget)
        self.homelabel.setGeometry(QtCore.QRect(191, 62, 61, 16))
        self.homelabel.setObjectName("homelabel")
        self.labelCap_9 = QtWidgets.QLabel(self.centralwidget)
        self.labelCap_9.setGeometry(QtCore.QRect(20, 85, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelCap_9.setFont(font)
        self.labelCap_9.setObjectName("labelCap_9")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 80, 331, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.con_disconnect_bt = QtWidgets.QPushButton(self.centralwidget)
        self.con_disconnect_bt.setGeometry(QtCore.QRect(450, 40, 61, 23))
        self.con_disconnect_bt.setObjectName("con_disconnect_bt")
        self.con_disconnect_bt.setEnabled(False)
        self.prt_movezval_sel = QtWidgets.QComboBox(self.centralwidget)
        self.prt_movezval_sel.setGeometry(QtCore.QRect(217, 180, 52, 22))
        self.prt_movezval_sel.setEditable(True)
        self.prt_movezval_sel.setObjectName("prt_movezval_sel")
        self.prt_movezval_sel.addItem("")
        self.prt_movezval_sel.addItem("")
        self.prt_movezval_sel.addItem("")
        self.prt_movezval_sel.addItem("")
        self.prt_movezval_sel.addItem("")
        self.prt_movezval_sel.setEnabled(False)
        self.displays = QtWidgets.QWidget(self.centralwidget)
        self.displays.setGeometry(QtCore.QRect(380, 430, 481, 211))
        self.displays.setObjectName("displays")
        self.camThread_start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.camThread_start_btn.setGeometry(QtCore.QRect(380, 370, 71, 23))
        self.camThread_start_btn.setObjectName("camThread_start_btn")
        self.camThread_stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.camThread_stop_btn.setGeometry(QtCore.QRect(460, 370, 71, 23))
        self.camThread_stop_btn.setObjectName("camThread_stop_btn")
        self.cam_no_sel = QtWidgets.QComboBox(self.centralwidget)
        self.cam_no_sel.setGeometry(QtCore.QRect(636, 369, 52, 22))
        self.cam_no_sel.setEditable(True)
        self.cam_no_sel.setObjectName("cam_no_sel")
        self.cam_no_sel.addItem("")
        self.cam_no_sel.addItem("")
        self.cam_no_sel.addItem("")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(580, 369, 41, 20))
        self.label_14.setObjectName("label_14")
        self.cam_exp_sel = QtWidgets.QComboBox(self.centralwidget)
        self.cam_exp_sel.setGeometry(QtCore.QRect(750, 369, 81, 22))
        self.cam_exp_sel.setEditable(True)
        self.cam_exp_sel.setObjectName("cam_exp_sel")
        self.cam_exp_sel.addItem("")
        self.cam_exp_sel.addItem("")
        self.cam_exp_sel.addItem("")
        self.cam_exp_sel.addItem("")
        self.cam_exp_sel.addItem("")
        self.cam_exp_sel.addItem("")
        self.cam_exp_sel.addItem("")
        self.cam_exp_sel.addItem("")
        self.cam_exp_sel.addItem("")
        self.cam_exp_sel.addItem("")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(700, 369, 41, 20))
        self.label_15.setObjectName("label_15")
        self.cam_img_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cam_img_btn.setGeometry(QtCore.QRect(380, 406, 81, 19))
        self.cam_img_btn.setObjectName("cam_img_btn")
        self.labelCap_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelCap_2.setGeometry(QtCore.QRect(380, 340, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelCap_2.setFont(font)
        self.labelCap_2.setObjectName("labelCap_2")
        self.prt_stat_gv = QtWidgets.QGraphicsView(self.centralwidget)
        self.prt_stat_gv.setGeometry(QtCore.QRect(140, 7, 21, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.prt_stat_gv.setPalette(palette)
        self.prt_stat_gv.setObjectName("prt_stat_gv")
        self.con_stat_gv = QtWidgets.QGraphicsView(self.centralwidget)
        self.con_stat_gv.setEnabled(True)
        self.con_stat_gv.setGeometry(QtCore.QRect(520, 40, 21, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.con_stat_gv.setPalette(palette)
        self.con_stat_gv.setObjectName("con_stat_gv")
        self.cam_stat_gv = QtWidgets.QGraphicsView(self.centralwidget)
        self.cam_stat_gv.setGeometry(QtCore.QRect(540, 370, 21, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.cam_stat_gv.setPalette(palette)
        self.cam_stat_gv.setObjectName("cam_stat_gv")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(747, 41, 51, 20))
        self.label_5.setObjectName("label_5")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(380, 326, 481, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(652, 404, 51, 20))
        self.label_16.setObjectName("label_16")
        self.cam_rr_sel = QtWidgets.QComboBox(self.centralwidget)
        self.cam_rr_sel.setGeometry(QtCore.QRect(709, 404, 52, 22))
        self.cam_rr_sel.setEditable(True)
        self.cam_rr_sel.setObjectName("cam_rr_sel")
        self.cam_rr_sel.addItem("")
        self.cam_rr_sel.addItem("")
        self.cam_rr_sel.addItem("")
        self.cam_rr_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.cam_rr_lcd.setGeometry(QtCore.QRect(769, 403, 64, 23))
        palette = QtGui.QPalette()
        self.cam_rr_lcd.setPalette(palette)
        self.cam_rr_lcd.setStyleSheet("")
        self.cam_rr_lcd.setObjectName("cam_rr_lcd")
        self.conPltRange = QtWidgets.QSlider(self.centralwidget)
        self.conPltRange.setGeometry(QtCore.QRect(640, 310, 111, 20))
        self.conPltRange.setMinimum(1)
        self.conPltRange.setMaximum(180)
        self.conPltRange.setPageStep(60)
        self.conPltRange.setSliderPosition(180)
        self.conPltRange.setOrientation(QtCore.Qt.Horizontal)
        self.conPltRange.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.conPltRange.setTickInterval(60)
        self.conPltRange.setObjectName("conPltRange")
        
        ##CONDUCTANCE TAB
        self.con_threshold_sp = QtWidgets.QSpinBox(self.centralwidget)
        self.con_threshold_sp.setGeometry(QtCore.QRect(760, 306, 61, 22))
        self.con_threshold_sp.setMaximum(1023)
        self.con_threshold_sp.setProperty("value", 100)                                 #set at 100
        self.con_threshold_sp.setObjectName("con_threshold_sp")
        
        
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 290, 341, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.labelCap_17 = QtWidgets.QLabel(self.tab)
        self.labelCap_17.setGeometry(QtCore.QRect(150, 290, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelCap_17.setFont(font)
        self.labelCap_17.setObjectName("labelCap_17")
        self.gc_setx_sel = QtWidgets.QSpinBox(self.tab)
        self.gc_setx_sel.setGeometry(QtCore.QRect(87, 81, 61, 22))
        self.gc_setx_sel.setMinimum(1)
        self.gc_setx_sel.setProperty("value", 5)
        self.gc_setx_sel.setObjectName("gc_setx_sel")
        self.labelCap_12 = QtWidgets.QLabel(self.tab)
        self.labelCap_12.setGeometry(QtCore.QRect(77, 80, 20, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCap_12.setFont(font)
        self.labelCap_12.setObjectName("labelCap_12")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(10, 112, 51, 16))
        self.label_9.setObjectName("label_9")
        self.labelCap_6 = QtWidgets.QLabel(self.tab)
        self.labelCap_6.setGeometry(QtCore.QRect(77, 53, 20, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCap_6.setFont(font)
        self.labelCap_6.setObjectName("labelCap_6")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(10, 79, 61, 16))
        self.label_8.setObjectName("label_8")
        self.labelCap_14 = QtWidgets.QLabel(self.tab)
        self.labelCap_14.setGeometry(QtCore.QRect(77, 109, 20, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCap_14.setFont(font)
        self.labelCap_14.setObjectName("labelCap_14")
        self.gc_startz_sel = QtWidgets.QDoubleSpinBox(self.tab)
        self.gc_startz_sel.setGeometry(QtCore.QRect(267, 53, 62, 22))
        self.gc_startz_sel.setMaximum(250.0)
        self.gc_startz_sel.setProperty("value", 5.0)
        self.gc_startz_sel.setObjectName("gc_startz_sel")
        self.gc_gen_btn = QtWidgets.QPushButton(self.tab)
        self.gc_gen_btn.setGeometry(QtCore.QRect(10, 308, 91, 23))
        self.gc_gen_btn.setObjectName("gc_gen_btn")
        self.labelCap_15 = QtWidgets.QLabel(self.tab)
        self.labelCap_15.setGeometry(QtCore.QRect(167, 109, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCap_15.setFont(font)
        self.labelCap_15.setObjectName("labelCap_15")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(10, 144, 121, 16))
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 56, 81, 16))
        self.label_7.setObjectName("label_7")
        self.labelCap_13 = QtWidgets.QLabel(self.tab)
        self.labelCap_13.setGeometry(QtCore.QRect(167, 81, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCap_13.setFont(font)
        self.labelCap_13.setObjectName("labelCap_13")
        self.gc_currenty_btn = QtWidgets.QPushButton(self.tab)
        self.gc_currenty_btn.setGeometry(QtCore.QRect(177, 33, 61, 21))
        self.gc_currenty_btn.setObjectName("gc_currenty_btn")
        self.gc_retz_sel = QtWidgets.QDoubleSpinBox(self.tab)
        self.gc_retz_sel.setGeometry(QtCore.QRect(191, 257, 51, 22))
        self.gc_retz_sel.setObjectName("gc_retz_sel")
        self.gc_currentlz_btn = QtWidgets.QPushButton(self.tab)
        self.gc_currentlz_btn.setGeometry(QtCore.QRect(241, 227, 61, 24))
        self.gc_currentlz_btn.setObjectName("gc_currentlz_btn")
        self.labelCap_7 = QtWidgets.QLabel(self.tab)
        self.labelCap_7.setGeometry(QtCore.QRect(167, 53, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCap_7.setFont(font)
        self.labelCap_7.setObjectName("labelCap_7")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(125, 252, 51, 20))
        self.label_13.setObjectName("label_13")
        self.gc_starty_sel = QtWidgets.QDoubleSpinBox(self.tab)
        self.gc_starty_sel.setGeometry(QtCore.QRect(177, 53, 62, 22))
        self.gc_starty_sel.setMaximum(250.0)
        self.gc_starty_sel.setObjectName("gc_starty_sel")
        self.labelCap_11 = QtWidgets.QLabel(self.tab)
        self.labelCap_11.setGeometry(QtCore.QRect(257, 53, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCap_11.setFont(font)
        self.labelCap_11.setObjectName("labelCap_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(124, 230, 71, 16))
        self.label_12.setObjectName("label_12")
        self.gc_currentx_btn = QtWidgets.QPushButton(self.tab)
        self.gc_currentx_btn.setGeometry(QtCore.QRect(87, 33, 61, 21))
        self.gc_currentx_btn.setObjectName("gc_currentx_btn")
        self.gc_lz_sel = QtWidgets.QDoubleSpinBox(self.tab)
        self.gc_lz_sel.setGeometry(QtCore.QRect(191, 228, 51, 22))
        self.gc_lz_sel.setProperty("value", 1.0)
        self.gc_lz_sel.setObjectName("gc_lz_sel")
        self.gc_modefalse_rb = QtWidgets.QRadioButton(self.tab)
        self.gc_modefalse_rb.setGeometry(QtCore.QRect(10, 230, 111, 16))
        self.gc_modefalse_rb.setChecked(True)
        self.gc_modefalse_rb.setObjectName("gc_modefalse_rb")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(260, 110, 71, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(173, 144, 51, 16))
        self.label_11.setObjectName("label_11")
        self.gc_modetrue_rb = QtWidgets.QRadioButton(self.tab)
        self.gc_modetrue_rb.setGeometry(QtCore.QRect(10, 258, 111, 16))
        self.gc_modetrue_rb.setObjectName("gc_modetrue_rb")
        self.gc_currentall_btn = QtWidgets.QPushButton(self.tab)
        self.gc_currentall_btn.setGeometry(QtCore.QRect(6, 33, 76, 21))
        self.gc_currentall_btn.setObjectName("gc_currentall_btn")
        self.gc_currentz_btn = QtWidgets.QPushButton(self.tab)
        self.gc_currentz_btn.setGeometry(QtCore.QRect(267, 33, 61, 21))
        self.gc_currentz_btn.setObjectName("gc_currentz_btn")
        self.labelCap_10 = QtWidgets.QLabel(self.tab)
        self.labelCap_10.setGeometry(QtCore.QRect(10, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelCap_10.setFont(font)
        self.labelCap_10.setObjectName("labelCap_10")
        self.gc_sety_sel = QtWidgets.QSpinBox(self.tab)
        self.gc_sety_sel.setGeometry(QtCore.QRect(177, 81, 61, 22))
        self.gc_sety_sel.setMinimum(1)
        self.gc_sety_sel.setProperty("value", 1)
        self.gc_sety_sel.setObjectName("gc_sety_sel")
        self.gc_startx_sel = QtWidgets.QDoubleSpinBox(self.tab)
        self.gc_startx_sel.setGeometry(QtCore.QRect(87, 53, 62, 22))
        self.gc_startx_sel.setMaximum(250.0)
        self.gc_startx_sel.setObjectName("gc_startx_sel")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(10, 89, 71, 16))
        self.label_27.setObjectName("label_27")
        self.prt_startrun_btn = QtWidgets.QPushButton(self.tab)
        self.prt_startrun_btn.setGeometry(QtCore.QRect(239, 290, 91, 41))
        self.prt_startrun_btn.setObjectName("prt_startrun_btn")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(10, 153, 71, 16))
        self.label_19.setObjectName("label_19")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(173, 153, 61, 16))
        self.label_22.setObjectName("label_22")
        self.gc_resx_sel = QtWidgets.QDoubleSpinBox(self.tab)
        self.gc_resx_sel.setGeometry(QtCore.QRect(88, 108, 61, 22))
        self.gc_resx_sel.setMinimum(0)
        self.gc_resx_sel.setMaximum(250.0)
        self.gc_resx_sel.setProperty("value", 2.0)
        self.gc_resx_sel.setObjectName("gc_resx_sel")
        self.gc_resy_sel = QtWidgets.QDoubleSpinBox(self.tab)
        self.gc_resy_sel.setGeometry(QtCore.QRect(177, 109, 61, 22))
        self.gc_resy_sel.setMinimum(0)
        self.gc_resy_sel.setMaximum(250.0)
        self.gc_resy_sel.setProperty("value", 2.0)
        self.gc_resy_sel.setObjectName("gc_resy_sel")
        self.gc_zspeedup_sel = QtWidgets.QSpinBox(self.tab)
        self.gc_zspeedup_sel.setGeometry(QtCore.QRect(150, 175, 61, 22))
        self.gc_zspeedup_sel.setMaximum(1700)
        self.gc_zspeedup_sel.setProperty("value", 720)
        self.gc_zspeedup_sel.setObjectName("gc_zspeedup_sel")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(10, 167, 71, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(10, 187, 71, 16))
        self.label_29.setObjectName("label_29")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(120, 173, 31, 16))
        self.label_31.setObjectName("label_31")
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(10, 177, 51, 16))
        self.label_30.setObjectName("label_30")
        self.label_32 = QtWidgets.QLabel(self.tab)
        self.label_32.setGeometry(QtCore.QRect(120, 183, 21, 16))
        self.label_32.setObjectName("label_32")
        self.gc_speedxy_sel = QtWidgets.QSpinBox(self.tab)
        self.gc_speedxy_sel.setGeometry(QtCore.QRect(268, 175, 61, 22))
        self.gc_speedxy_sel.setMaximum(20800) #was 10800
        self.gc_speedxy_sel.setProperty("value", 5000)
        self.gc_speedxy_sel.setObjectName("gc_speedxy_sel")
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setGeometry(QtCore.QRect(232, 172, 31, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setGeometry(QtCore.QRect(232, 182, 31, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(255, 258, 41, 20))
        self.label_35.setObjectName("label_35")
        self.gc_zoff_sel = QtWidgets.QDoubleSpinBox(self.tab)
        self.gc_zoff_sel.setGeometry(QtCore.QRect(288, 256, 41, 22))
        self.gc_zoff_sel.setObjectName("gc_zoff_sel")
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setGeometry(QtCore.QRect(124, 261, 71, 20))
        self.label_36.setObjectName("label_36")
        self.pump_stat_gv_2 = QtWidgets.QGraphicsView(self.tab)
        self.pump_stat_gv_2.setEnabled(True)
        self.pump_stat_gv_2.setGeometry(QtCore.QRect(100, 309, 22, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.pump_stat_gv_2.setPalette(palette)
        self.pump_stat_gv_2.setObjectName("pump_stat_gv_2")
        self.gc_st_sel = QtWidgets.QDoubleSpinBox(self.tab)
        self.gc_st_sel.setGeometry(QtCore.QRect(88, 147, 61, 22))
        self.gc_st_sel.setMaximum(250.0)
        self.gc_st_sel.setProperty("value", 5.0)
        self.gc_st_sel.setObjectName("gc_st_sel")
        self.gc_pause_sel = QtWidgets.QDoubleSpinBox(self.tab)
        self.gc_pause_sel.setGeometry(QtCore.QRect(221, 147, 61, 22))
        self.gc_pause_sel.setMaximum(250.0)
        self.gc_pause_sel.setProperty("value", 6.0)
        self.gc_pause_sel.setObjectName("gc_pause_sel")
        self.gc_filename_txt = QtWidgets.QLineEdit(self.tab)
        self.gc_filename_txt.setGeometry(QtCore.QRect(11, 289, 111, 21))
        self.gc_filename_txt.setObjectName("gc_filename_txt")
        self.gc_zspeed_sel = QtWidgets.QDoubleSpinBox(self.tab)
        self.gc_zspeed_sel.setGeometry(QtCore.QRect(50, 177, 61, 22))
        self.gc_zspeed_sel.setMaximum(1000.0)
        self.gc_zspeed_sel.setSingleStep(0.01)
        self.gc_zspeed_sel.setProperty("value", 1.0)
        self.gc_zspeed_sel.setObjectName("gc_zspeed_sel")
        self.label_39 = QtWidgets.QLabel(self.tab)
        self.label_39.setGeometry(QtCore.QRect(10, 210, 61, 16))
        self.label_39.setObjectName("label_39")
        self.gc_step_sel = QtWidgets.QDoubleSpinBox(self.tab)
        self.gc_step_sel.setGeometry(QtCore.QRect(80, 210, 61, 22))
        self.gc_step_sel.setDecimals(3)
        self.gc_step_sel.setMinimum(0.001)
        self.gc_step_sel.setMaximum(1.0)
        self.gc_step_sel.setSingleStep(0.01)
        self.gc_step_sel.setProperty("value", 0.05)
        self.gc_step_sel.setObjectName("gc_step_sel")
        self.labelCap_17.raise_()
        self.labelCap_12.raise_()
        self.label_9.raise_()
        self.labelCap_6.raise_()
        self.label_8.raise_()
        self.labelCap_14.raise_()
        self.gc_gen_btn.raise_()
        self.labelCap_15.raise_()
        self.label_10.raise_()
        self.label_7.raise_()
        self.labelCap_13.raise_()
        self.gc_currenty_btn.raise_()
        self.gc_currentlz_btn.raise_()
        self.labelCap_7.raise_()
        self.label_13.raise_()
        self.labelCap_11.raise_()
        self.label_12.raise_()
        self.gc_currentx_btn.raise_()
        self.gc_modefalse_rb.raise_()
        self.checkBox_2.raise_()
        self.label_11.raise_()
        self.gc_modetrue_rb.raise_()
        self.gc_currentall_btn.raise_()
        self.gc_currentz_btn.raise_()
        self.labelCap_10.raise_()
        self.label_27.raise_()
        self.prt_startrun_btn.raise_()
        self.label_19.raise_()
        self.label_22.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_31.raise_()
        self.label_30.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.pump_stat_gv_2.raise_()
        self.gc_filename_txt.raise_()
        self.gc_zspeedup_sel.raise_()
        self.gc_speedxy_sel.raise_()
        self.gc_startz_sel.raise_()
        self.gc_startx_sel.raise_()
        self.gc_pause_sel.raise_()
        self.gc_resy_sel.raise_()
        self.gc_retz_sel.raise_()
        self.gc_starty_sel.raise_()
        self.gc_st_sel.raise_()
        self.gc_setx_sel.raise_()
        self.gc_sety_sel.raise_()
        self.gc_resx_sel.raise_()
        self.gc_lz_sel.raise_()
        self.gc_zoff_sel.raise_()
        self.gc_zspeed_sel.raise_()
        self.label_39.raise_()
        self.gc_step_sel.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.labelCap_18 = QtWidgets.QLabel(self.tab_2)
        self.labelCap_18.setGeometry(QtCore.QRect(10, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelCap_18.setFont(font)
        self.labelCap_18.setObjectName("labelCap_18")
        self.pump_baud_sel = QtWidgets.QComboBox(self.tab_2)
        self.pump_baud_sel.setEnabled(True)
        self.pump_baud_sel.setGeometry(QtCore.QRect(270, 50, 52, 22))
        self.pump_baud_sel.setEditable(True)
        self.pump_baud_sel.setObjectName("pump_baud_sel")
        self.pump_baud_sel.addItem("")
        self.pump_baud_sel.addItem("")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(150, 50, 21, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(240, 51, 31, 20))
        self.label_18.setObjectName("label_18")
        self.pump_stat_gv = QtWidgets.QGraphicsView(self.tab_2)
        self.pump_stat_gv.setEnabled(True)
        self.pump_stat_gv.setGeometry(QtCore.QRect(142, 16, 21, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.pump_stat_gv.setPalette(palette)
        self.pump_stat_gv.setObjectName("pump_stat_gv")
        self.pump_com_sel = QtWidgets.QComboBox(self.tab_2)
        self.pump_com_sel.setGeometry(QtCore.QRect(180, 50, 52, 22))
        self.pump_com_sel.setEditable(True)
        self.pump_com_sel.setObjectName("pump_com_sel")
        self.pump_com_sel.addItem("")
        self.pump_com_sel.addItem("")
        self.pump_com_sel.addItem("")
        self.pump_com_sel.addItem("")
        self.pump_com_sel.addItem("")
        self.pump_com_sel.addItem("")
        self.pump_com_sel.addItem("")
        self.pump_con_btn = QtWidgets.QPushButton(self.tab_2)
        self.pump_con_btn.setGeometry(QtCore.QRect(10, 50, 61, 23))
        self.pump_con_btn.setObjectName("pump_con_btn")
        self.pump_discon_btn = QtWidgets.QPushButton(self.tab_2)
        self.pump_discon_btn.setGeometry(QtCore.QRect(80, 50, 61, 23))
        self.pump_discon_btn.setObjectName("pump_discon_btn")
        self.pump_setq_btn = QtWidgets.QPushButton(self.tab_2)
        self.pump_setq_btn.setGeometry(QtCore.QRect(90, 100, 61, 23))
        self.pump_setq_btn.setObjectName("pump_setq_btn")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 160, 81, 16))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 180, 81, 16))
        self.radioButton_4.setObjectName("radioButton_4")
        self.pump_samplingq_sel = QtWidgets.QSpinBox(self.tab_2)
        self.pump_samplingq_sel.setGeometry(QtCore.QRect(100, 210, 42, 22))
        self.pump_samplingq_sel.setMaximum(1000)
        self.pump_samplingq_sel.setSingleStep(5)
        self.pump_samplingq_sel.setProperty("value", 150)
        self.pump_samplingq_sel.setObjectName("pump_samplingq_sel")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(10, 210, 81, 16))
        self.label_20.setObjectName("label_20")
        self.pump_dwellq_sel = QtWidgets.QSpinBox(self.tab_2)
        self.pump_dwellq_sel.setGeometry(QtCore.QRect(100, 236, 42, 20))
        self.pump_dwellq_sel.setMaximum(1000)
        self.pump_dwellq_sel.setSingleStep(5)
        self.pump_dwellq_sel.setProperty("value", 40)
        self.pump_dwellq_sel.setObjectName("pump_dwellq_sel")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(10, 238, 81, 14))
        self.label_21.setObjectName("label_21")
        self.pump_flowrate_sel = QtWidgets.QSpinBox(self.tab_2)
        self.pump_flowrate_sel.setGeometry(QtCore.QRect(10, 100, 41, 22))
        self.pump_flowrate_sel.setMaximum(999)
        self.pump_flowrate_sel.setSingleStep(5)
        self.pump_flowrate_sel.setProperty("value", 80)
        self.pump_flowrate_sel.setObjectName("pump_flowrate_sel")
        self.pump_start_btn = QtWidgets.QPushButton(self.tab_2)
        self.pump_start_btn.setGeometry(QtCore.QRect(182, 130, 61, 23))
        self.pump_start_btn.setObjectName("pump_start_btn")
        self.pump_stop_btn = QtWidgets.QPushButton(self.tab_2)
        self.pump_stop_btn.setGeometry(QtCore.QRect(250, 130, 61, 23))
        self.pump_stop_btn.setObjectName("pump_stop_btn")
        self.con_connect_bt_4 = QtWidgets.QPushButton(self.tab_2)
        self.con_connect_bt_4.setGeometry(QtCore.QRect(87, 130, 81, 23))
        self.con_connect_bt_4.setObjectName("con_connect_bt_4")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(56, 101, 41, 20))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(67, 130, 21, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(223, 101, 41, 20))
        self.label_26.setObjectName("label_26")
        self.pump_v_sel = QtWidgets.QSpinBox(self.tab_2)
        self.pump_v_sel.setGeometry(QtCore.QRect(177, 100, 41, 22))
        self.pump_v_sel.setMaximum(999)
        self.pump_v_sel.setSingleStep(5)
        self.pump_v_sel.setProperty("value", 10)
        self.pump_v_sel.setObjectName("pump_v_sel")
        self.con_connect_bt_5 = QtWidgets.QPushButton(self.tab_2)
        self.con_connect_bt_5.setGeometry(QtCore.QRect(237, 100, 61, 23))
        self.con_connect_bt_5.setObjectName("con_connect_bt_5")
        self.pump_syringed_sel = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.pump_syringed_sel.setGeometry(QtCore.QRect(10, 130, 51, 22))
        self.pump_syringed_sel.setProperty("value", 14.57)
        self.pump_syringed_sel.setObjectName("pump_syringed_sel")
        self.tabWidget.addTab(self.tab_2, "")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 275, 331, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.prt_discon_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_discon_btn.setGeometry(QtCore.QRect(90, 30, 71, 23))
        self.prt_discon_btn.setObjectName("prt_discon_btn")
        self.prt_home_stat_gv = QtWidgets.QGraphicsView(self.centralwidget)
        self.prt_home_stat_gv.setEnabled(False)
        self.prt_home_stat_gv.setGeometry(QtCore.QRect(260, 60, 21, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.prt_home_stat_gv.setPalette(palette)
        self.prt_home_stat_gv.setObjectName("prt_home_stat_gv")
        self.prt_moving_gv = QtWidgets.QGraphicsView(self.centralwidget)
        self.prt_moving_gv.setEnabled(True)
        self.prt_moving_gv.setGeometry(QtCore.QRect(170, 180, 21, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.prt_moving_gv.setPalette(palette)
        self.prt_moving_gv.setObjectName("prt_moving_gv")
        self.prt_poszero_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_poszero_btn.setGeometry(QtCore.QRect(280, 90, 61, 23))
        self.prt_poszero_btn.setObjectName("prt_poszero_btn")
        self.prt_poszero_btn.setEnabled(False)
        self.prt_con_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_con_btn.setGeometry(QtCore.QRect(20, 30, 61, 23))
        self.prt_con_btn.setObjectName("prt_con_btn")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(350, 10, 20, 631))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(110, 230, 81, 16))
        self.label_23.setObjectName("label_23")
        self.prt_fast_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_fast_btn.setGeometry(QtCore.QRect(280, 160, 61, 23))
        self.prt_fast_btn.setObjectName("prt_fast_btn")
        self.prt_fast_btn.setEnabled(False)
        self.prt_slow_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_slow_btn.setGeometry(QtCore.QRect(280, 180, 61, 23))
        self.prt_slow_btn.setObjectName("prt_slow_btn")
        self.prt_slow_btn.setEnabled(False)
        self.prt_movexyval_sel = QtWidgets.QComboBox(self.centralwidget)
        self.prt_movexyval_sel.setGeometry(QtCore.QRect(67, 180, 52, 22))
        self.prt_movexyval_sel.setEditable(True)
        self.prt_movexyval_sel.setObjectName("prt_movexyval_sel")
        self.prt_movexyval_sel.addItem("")
        self.prt_movexyval_sel.addItem("")
        self.prt_movexyval_sel.addItem("")
        self.prt_movexyval_sel.addItem("")
        self.prt_movexyval_sel.addItem("")
        self.prt_movexyval_sel.setEnabled(False)
        self.conThread_save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.conThread_save_btn.setGeometry(QtCore.QRect(578, 300, 51, 23))
        self.conThread_save_btn.setObjectName("conThread_save_btn")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(640, 296, 81, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(760, 293, 81, 16))
        self.label_38.setObjectName("label_38")
        self.prt_poshundred_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_poshundred_btn.setGeometry(QtCore.QRect(280, 115, 61, 23))
        self.prt_poshundred_btn.setObjectName("prt_poshundred_btn")
        self.prt_poshundred_btn.setEnabled(False)
        
        #stop button for printer
        self.prt_stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_stop_btn.setGeometry(QtCore.QRect(20, 660, 113, 32))
        self.prt_stop_btn.setObjectName("prt_stop_btn")
        self.prt_stop_btn.setText("Stop")

        
        #pause button for printer
        self.prt_pause_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_pause_btn.setGeometry(QtCore.QRect(140, 660, 113, 32))
        self.prt_pause_btn.setObjectName("prt_pause_btn")
        self.prt_pause_btn.setText("Pause")
        
        #update button for port printer
        
        self.prt_update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.prt_update_btn.setGeometry(QtCore.QRect(290,50, 71, 31))
        self.prt_update_btn.setObjectName("prt_update_btn")
        self.prt_update_btn.setText("Update")
        
        #update button for port conductance
        self.con_update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.con_update_btn.setGeometry(QtCore.QRect(550, 10, 71, 31))
        self.con_update_btn.setObjectName("con_update_btn")
        self.con_update_btn.setText("Update")
        
        #zero text
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(830, 290, 60, 16))
        self.label_40.setObjectName("label_40")
        
        #zero button
        self.con_zero_btn = QtWidgets.QSpinBox(self.centralwidget)
        self.con_zero_btn.setGeometry(QtCore.QRect(830, 310, 42, 22))
        self.con_zero_btn.setObjectName("con_zero_btn")
        self.con_zero_btn.setMaximum(1023)
        self.con_zero_btn.setProperty("value", 0)
        
        #
        self.labelCap_16 = QtWidgets.QLabel(self.centralwidget)
        self.labelCap_16.setGeometry(QtCore.QRect(870, 10, 11, 31))
        self.labelCap_16.setObjectName("labelCap_16")
        
        self.prt_bed_temp_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.prt_bed_temp_lcd.setGeometry(QtCore.QRect(880, 40, 64, 23))
        self.prt_bed_temp_lcd.setObjectName("prt_bed_temp_lcd")
        self.prt_bed_temp_lcd.display(0)
        
        self.prt_nozzel_temp_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.prt_nozzel_temp_lcd.setGeometry(QtCore.QRect(970, 40, 64, 23))
        self.prt_nozzel_temp_lcd.setObjectName("prt_nozzel_temp_lcd")
        self.prt_nozzel_temp_lcd.display(0)
        
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(880, 70, 61, 20))
        self.label_6.setObjectName("label_6")
        
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(970, 70, 81, 20))
        self.label_41.setObjectName("label_41")
        
        self.prt_bed_temp_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.prt_bed_temp_sb.setGeometry(QtCore.QRect(880, 90, 62, 22))
        self.prt_bed_temp_sb.setObjectName("prt_bed_temp_sb")
        self.prt_bed_temp_sb.setMaximum(150)
        self.prt_bed_temp_sb.setProperty("value", 0)
        
        self.prt_nozzel_temp_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.prt_nozzel_temp_sb.setGeometry(QtCore.QRect(970, 90, 62, 22))
        self.prt_nozzel_temp_sb.setObjectName("prt_nozzel_temp_sb")
        self.prt_nozzel_temp_sb.setMaximum(250)
        self.prt_nozzel_temp_sb.setProperty("value", 0)
        
        self.label_cap_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_cap_16.setGeometry(QtCore.QRect(870, 10, 141, 31))
        self.label_cap_16.setObjectName("label_cap_16")
        
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(880, 70, 31, 20))
        self.label_6.setObjectName("label_6")
        
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(970, 70, 51, 20))
        self.label_41.setObjectName("label_41")
        
        self.temp_start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.temp_start_btn.setGeometry(QtCore.QRect(870,120,61,32))
        self.temp_start_btn.setObjectName("temp_start_btn")
        self.temp_start_btn.setText("Start")

        self.nozzel_temp_start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.nozzel_temp_start_btn.setGeometry(QtCore.QRect(960,120,61,32))
        self.nozzel_temp_start_btn.setObjectName("nozzel_temp_start_btn")
        self.nozzel_temp_start_btn.setText("Start")
        
        
        self.labelCap_19 = QtWidgets.QLabel(self.centralwidget)
        self.labelCap_19.setGeometry(QtCore.QRect(10, 680, 111, 31))
        self.labelCap_19.setObjectName("labelCap_19")
        
        self.ref_on_off_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ref_on_off_btn.setGeometry(QtCore.QRect(130, 680, 111, 31))
        self.ref_on_off_btn.setObjectName("ref_on_off_btn")
        self.ref_on_off_btn.setCheckable(True)
        self.ref_on_off_btn.isChecked()
        self.ref_on_off_btn.setText("start")
        
        self.ref_set_select = QtWidgets.QRadioButton(self.centralwidget)
        self.ref_set_select.setGeometry(QtCore.QRect(30,710,100,20))
        self.ref_set_select.setObjectName("ref_set_select")
        self.ref_set_select.setChecked(True)
        
        self.ref_conductance_select = QtWidgets.QRadioButton(self.centralwidget)
        self.ref_conductance_select.setGeometry(QtCore.QRect(30,730,100,20))
        self.ref_conductance_select.setObjectName("ref_conductance_select")#need to make independant from eachother
        
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(130, 710,81, 16))
        self.label_42.setObjectName("label_42")
        
        self.ref_z_lower = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ref_z_lower.setGeometry(QtCore.QRect(220, 710, 51, 22))
        self.ref_z_lower.setObjectName("ref_z_lower")
        
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(130, 730, 81, 16))
        self.label_43.setObjectName("label_43")
        
        self.ref_z_retract = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ref_z_retract.setGeometry(QtCore.QRect(220, 730,51, 22))
        self.ref_z_retract.setObjectName("ref_z_retract")
        
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(280,730,51,22))
        self.label_44.setObjectName("label_44")
        
        self.ref_z_offset = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ref_z_offset.setGeometry(QtCore.QRect(330, 730, 51, 22))
        self.ref_z_offset.setObjectName("ref_z_offset")
        
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(100,760,16,16))
        self.label_45.setObjectName("label_45")
        
        self.ref_x_pos = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ref_x_pos.setGeometry(QtCore.QRect(120,760,51,22))
        self.ref_x_pos.setObjectName("ref_x_pos")
        self.ref_x_pos.setMaximum(300)
        
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(190,760,16,16))
        self.label_46.setObjectName("label_46")
        
        self.ref_y_pos = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ref_y_pos.setGeometry(QtCore.QRect(210,760,51,22))
        self.ref_y_pos.setObjectName("ref_y_pos")
        self.ref_y_pos.setMaximum(300)
        
         # Create a QButtonGroup
        self.ref_mode = QtWidgets.QButtonGroup(self)
        self.ref_mode.setExclusive(True)

        # Add checkboxes to the button group
        self.ref_mode.addButton(self.ref_set_select)
        self.ref_mode.addButton(self.ref_conductance_select)
        
        
        
        
        
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(60,790,51,16))
        self.label_47.setObjectName("label_47")
        
        
        self.ref_sample = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ref_sample.setGeometry(QtCore.QRect(120, 790, 51, 22))
        self.ref_sample.setObjectName("ref_sample")
        
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(180,790,41,20))
        self.label_48.setObjectName("label_48")
        
        self.ref_dwell = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ref_dwell.setGeometry(QtCore.QRect(220, 790, 51, 22))
        self.ref_dwell.setObjectName("ref_dwell")
        
        self.resolution_mode = QtWidgets.QRadioButton(self.centralwidget)
        self.resolution_mode.setGeometry(QtCore.QRect(870, 170, 111, 16))
        self.resolution_mode.setObjectName("resolution_mode")
        
        self.dimension_mode = QtWidgets.QRadioButton(self.centralwidget)
        self.dimension_mode.setGeometry(QtCore.QRect(870, 190, 111, 16))
        self.dimension_mode.setObjectName("dimension_mode")
        
        self.label_86 = QtWidgets.QLabel(self.centralwidget)
        self.label_86.setGeometry(QtCore.QRect(1010,150,73,16))
        self.label_86.setObjectName("label_86")
        
        self.label_87 = QtWidgets.QLabel(self.centralwidget)
        self.label_87.setGeometry(QtCore.QRect(1120,150,81,20))
        self.label_87.setObjectName("label_87")

        self.res_x_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.res_x_lcd.setGeometry(QtCore.QRect(1010,170,64,23))
        self.res_x_lcd.setObjectName("res_x_lcd")
        
        self.res_y_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.res_y_lcd.setGeometry(QtCore.QRect(1120,170,64,23))
        self.res_y_lcd.setObjectName("res_y_lcd")
        
        self.label_88 = QtWidgets.QLabel(self.centralwidget)
        self.label_88.setGeometry(QtCore.QRect(1010,210,91,20))
        self.label_88.setObjectName("label_88")
        
        self.label_89 = QtWidgets.QLabel(self.centralwidget)
        self.label_89.setGeometry(QtCore.QRect(1120,210,91,20))
        self.label_89.setObjectName("label_89")
        
        self.dim_x_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.dim_x_lcd.setGeometry(QtCore.QRect(1010,230,64,23))
        self.dim_x_lcd.setObjectName("dim_x_lcd")
        
    
        self.dim_y_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.dim_y_lcd.setGeometry(QtCore.QRect(1120,230,64,23))
        self.dim_y_lcd.setObjectName("dim_y_lcd")
        
        self.label_90 = QtWidgets.QLabel(self.centralwidget)
        self.label_90.setGeometry(QtCore.QRect(900,280,81,16))
        self.label_90.setObjectName("label_90")
        
        self.dim_x_sb = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dim_x_sb.setGeometry(QtCore.QRect(1020,280,61,22))
        self.dim_x_sb.setObjectName("dim_x_sb")
        self.dim_x_sb.setProperty("value", 1)
        
        self.dim_y_sb = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dim_y_sb.setGeometry(QtCore.QRect(1130,280,61,22))
        self.dim_y_sb.setObjectName("dim_y_sb")
        self.dim_y_sb.setProperty("value", 1)
        
        self.x_pos_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.x_pos_sb.setGeometry(QtCore.QRect(950,370,62,22))
        self.x_pos_sb.setObjectName("x_pos_sb")

        self.y_pos_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.y_pos_sb.setGeometry(QtCore.QRect(1030,370,62,22))
        self.y_pos_sb.setObjectName("y_pos_sb")
        
        self.z_pos_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.z_pos_sb.setGeometry(QtCore.QRect(1110,370,62,22))
        self.z_pos_sb.setObjectName("z_pos_sb")
        
        self.x_pos_sb.setMaximum(300)
        self.y_pos_sb.setMaximum(300)
        self.z_pos_sb.setMaximum(300)
        
        self.send_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_btn.setGeometry(QtCore.QRect(1010,420,113,32))
        self.send_btn.setObjectName("send_btn")
        
        self.image_btn = QtWidgets.QPushButton(self.centralwidget)
        self.image_btn.setGeometry(QtCore.QRect(380,650,113,32))
        self.image_btn.setObjectName("image_btn")
        
        self.video_btn = QtWidgets.QPushButton(self.centralwidget)
        self.video_btn.setGeometry(QtCore.QRect(500,650,113,32))
        self.video_btn.setObjectName("video_btn")
        
         # Create a QButtonGroup
        self.calc_mode = QtWidgets.QButtonGroup(self)
        self.calc_mode.setExclusive(True)

        # Add checkboxes to the button group
        self.calc_mode.addButton(self.resolution_mode)
        self.calc_mode.addButton(self.dimension_mode)
        
        self.resolution_mode.setChecked(True)
        
        
        self.ref_set_select.setEnabled(False)
        self.ref_z_lower.setEnabled(False)
        self.ref_conductance_select.setEnabled(False)
        self.ref_z_retract.setEnabled(False)
        self.ref_z_offset.setEnabled(False)
        self.ref_x_pos.setEnabled(False)
        self.ref_y_pos.setEnabled(False)
        self.ref_sample.setEnabled(False)
        self.ref_dwell.setEnabled(False)
        
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1275, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.con_connect_bt.setEnabled(True)
        self.con_disconnect_bt.setEnabled(False)
        self.conThread_start_btn.setEnabled(False)
        self.conThread_stop_btn.setEnabled(False)
        self.conThread_save_btn.setEnabled(False)
        self.conPltRange.setEnabled(False)
        self.con_zero_btn.setEnabled(False)
        self.conThread_save_btn.setEnabled(False)
        self.con_threshold_sp.setEnabled(False)
        self.con_zero_btn.setEnabled(False)
        self.prt_nozzel_temp_sb.setEnabled(False)
        self.prt_bed_temp_sb.setEnabled(False)
        self.temp_start_btn.setEnabled(False)
        self.nozzel_temp_start_btn.setEnabled(False)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OPP Control"))
        self.labelCap.setText(_translate("MainWindow", "4. Conductance"))
        self.conThread_stop_btn.setText(_translate("MainWindow", "Stop Conductance"))
        self.prt_send_btn.setText(_translate("MainWindow", "Send G-Code"))
        self.labelCap_3.setText(_translate("MainWindow", "X"))
        self.labelCap_4.setText(_translate("MainWindow", "Y"))
        self.labelCap_5.setText(_translate("MainWindow", "Z"))
        self.prt_yp_btn.setText(_translate("MainWindow", "+"))
        self.prt_xp_btn.setText(_translate("MainWindow", "+"))
        self.prt_zp_btn.setText(_translate("MainWindow", "+"))
        self.prt_yn_btn.setText(_translate("MainWindow", "-"))
        self.prt_xn_btn.setText(_translate("MainWindow", "-"))
        self.prt_zn_btn.setText(_translate("MainWindow", "-"))
        
        
        if os.name == 'nt':
            # self.con_connect_bt.setText(_translate("MainWindow", "Connect"))
            # self.con_com_sel.setCurrentText(_translate("MainWindow", "COM1")) 
            # self.con_com_sel.setItemText(0, _translate("MainWindow", "COM1")) #sets item text to COM1
            # self.con_com_sel.setItemText(1, _translate("MainWindow", "COM2"))
            # self.con_com_sel.setItemText(2, _translate("MainWindow", "COM3"))
            # self.con_com_sel.setItemText(3, _translate("MainWindow", "COM4"))
            # self.con_com_sel.setItemText(4, _translate("MainWindow", "COM5"))
            # self.con_com_sel.setItemText(5, _translate("MainWindow", "COM6"))
            serial_ports = list(list_ports.comports())
            
            extracted_name =[ports.name for ports in serial_ports]
            extracted_ports = [ports.device for ports in serial_ports]
            self.con_com_sel.setCurrentText(_translate("MainWindow", str(extracted_ports)))
            #go through ports and add them to the dropdown
            for count, p in enumerate(extracted_ports):
                self.con_baud_sel_com_sel.setItemData(count, p)
                self.con_com_sel.setItemText(count, _translate("MainWindow", str(extracted_name[count])))
        else:
            # Set options for macOS
            
            serial_ports = list(list_ports.comports())
            
            
            #take off the everything after " - " in the port name
            extracted_ports = [str(port).split(' - ')[0] for port in serial_ports]
            extracted_name = [str(port).split(' - ')[1] for port in serial_ports]
            
            self.con_com_sel.setCurrentText(_translate("MainWindow", str(extracted_ports[0])))
            #go through ports and add them to the dropdown
            for count, p in enumerate(extracted_ports):
                self.con_com_sel.setItemData(count, p)
                self.con_com_sel.setItemText(count, _translate("MainWindow", str(extracted_name[count])))
                
                        
        self.label.setText(_translate("MainWindow", "Port:"))
        self.label_2.setText(_translate("MainWindow", "Baud:"))
        self.con_baud_sel.setItemText(0, _translate("MainWindow", "9600"))
        self.con_baud_sel.setItemText(1, _translate("MainWindow", "19200"))
        self.conThread_start_btn.setText(_translate("MainWindow", "Start Conductance"))
        self.labelCap_8.setText(_translate("MainWindow", "1. Printer Setup"))
        self.prt_home_btn.setText(_translate("MainWindow", "Home"))
        self.label_3.setText(_translate("MainWindow", "Port:"))
        
        if os.name == 'nt':
            # self.prt_com_sel.setCurrentText(_translate("MainWindow", "COM1"))
            # self.prt_com_sel.setItemText(0, _translate("MainWindow", "COM1"))
            # self.prt_com_sel.setItemText(1, _translate("MainWindow", "COM2"))
            # self.prt_com_sel.setItemText(2, _translate("MainWindow", "COM3"))
            # self.prt_com_sel.setItemText(3, _translate("MainWindow", "COM4"))
            # self.prt_com_sel.setItemText(4, _translate("MainWindow", "COM5"))
            # self.prt_com_sel.setItemText(5, _translate("MainWindow", "COM6"))
            selrial_ports = list(list_ports.comports())
            
            extracted_name =[ports.name for ports in serial_ports]
            extracted_ports = [ports.device for ports in serial_ports]
            self.prt_com_sel.setCurrentText(_translate("MainWindow", str(extracted_ports)))
            #go through ports and add them to the dropdown
            for count, p in enumerate(extracted_ports):
                self.prt_com_sel.setItemData(count, p)
                self.prt_com_sel.setItemText(count, _translate("MainWindow", str(extracted_name[count])))
            
        else:
            # Set options for macOS
            
            serial_ports = list(list_ports.comports())
            
            
            #take off the everything after " - " in the port name
            extracted_ports = [str(port).split(' - ')[0] for port in serial_ports]
            extracted_name = [str(port).split(' - ')[1] for port in serial_ports]
            
            self.prt_com_sel.setCurrentText(_translate("MainWindow", str(extracted_ports[0])))
            #go through ports and add them to the dropdown
            for count, p in enumerate(extracted_ports):
                self.prt_com_sel.setItemData(count, p)
                self.prt_com_sel.setItemText(count, _translate("MainWindow", str(extracted_name[count])))
        
        
        self.label_4.setText(_translate("MainWindow", "Baud:"))
        self.prt_baud_sel.setItemText(0, _translate("MainWindow", "9600"))
        self.prt_baud_sel.setItemText(1, _translate("MainWindow", "115200"))
        
        
        self.homelabel.setText(_translate("MainWindow", "Not homed"))
        self.labelCap_9.setText(_translate("MainWindow", "2. Sample Placement"))
        self.con_disconnect_bt.setText(_translate("MainWindow", "Disconnect"))
        self.prt_movezval_sel.setItemText(0, _translate("MainWindow", "0.01"))
        self.prt_movezval_sel.setItemText(1, _translate("MainWindow", "0.1"))
        self.prt_movezval_sel.setItemText(2, _translate("MainWindow", "1"))
        self.prt_movezval_sel.setItemText(3, _translate("MainWindow", "10"))
        self.prt_movezval_sel.setItemText(4, _translate("MainWindow", "100"))
        self.camThread_start_btn.setText(_translate("MainWindow", "Start Camera"))
        self.camThread_stop_btn.setText(_translate("MainWindow", "Stop Camera"))
        self.cam_no_sel.setCurrentText(_translate("MainWindow", "1"))
        self.cam_no_sel.setItemText(0, _translate("MainWindow", "1"))
        self.cam_no_sel.setItemText(1, _translate("MainWindow", "2"))
        self.cam_no_sel.setItemText(2, _translate("MainWindow", "3"))
        self.label_14.setText(_translate("MainWindow", "Camera:"))
        self.cam_exp_sel.setCurrentText(_translate("MainWindow", "0 (auto)"))
        self.cam_exp_sel.setItemText(0, _translate("MainWindow", "0 (auto)"))
        self.cam_exp_sel.setItemText(1, _translate("MainWindow", "-1 (640ms)"))
        self.cam_exp_sel.setItemText(2, _translate("MainWindow", "-2 (320ms)"))
        self.cam_exp_sel.setItemText(3, _translate("MainWindow", "-3 (160ms)"))
        self.cam_exp_sel.setItemText(4, _translate("MainWindow", "-4 (80ms)"))
        self.cam_exp_sel.setItemText(5, _translate("MainWindow", "-5 (40ms)"))
        self.cam_exp_sel.setItemText(6, _translate("MainWindow", "-6 (20ms)"))
        self.cam_exp_sel.setItemText(7, _translate("MainWindow", "-7 (10ms)"))
        self.cam_exp_sel.setItemText(8, _translate("MainWindow", "-8 (5ms)"))
        self.cam_exp_sel.setItemText(9, _translate("MainWindow", "-9 (2.5ms)"))
        self.label_15.setText(_translate("MainWindow", "Exposure:"))
        self.cam_img_btn.setText(_translate("MainWindow", "Capture Image"))
        self.labelCap_2.setText(_translate("MainWindow", "5. Camera"))
        self.label_5.setText(_translate("MainWindow", "Refreshrate:"))
        self.label_16.setText(_translate("MainWindow", "Refreshrate:"))
        self.cam_rr_sel.setCurrentText(_translate("MainWindow", "1"))
        self.cam_rr_sel.setItemText(0, _translate("MainWindow", "1"))
        self.cam_rr_sel.setItemText(1, _translate("MainWindow", "2"))
        self.cam_rr_sel.setItemText(2, _translate("MainWindow", "3"))
        self.labelCap_17.setText(_translate("MainWindow", "ETA"))
        self.labelCap_12.setText(_translate("MainWindow", "X"))
        self.label_9.setText(_translate("MainWindow", "Resolution"))
        self.labelCap_6.setText(_translate("MainWindow", "X"))
        self.label_8.setText(_translate("MainWindow", "Number of "))
        self.labelCap_14.setText(_translate("MainWindow", "X"))
        self.gc_gen_btn.setText(_translate("MainWindow", "Generate G-code"))
        self.labelCap_15.setText(_translate("MainWindow", "Y"))
        self.label_10.setText(_translate("MainWindow", "Sampling Time"))
        self.label_7.setText(_translate("MainWindow", "Start Position"))
        self.labelCap_13.setText(_translate("MainWindow", "Y"))
        self.gc_currenty_btn.setText(_translate("MainWindow", "Use Current"))
        self.gc_currentlz_btn.setText(_translate("MainWindow", "Use Current"))
        self.labelCap_7.setText(_translate("MainWindow", "Y"))
        self.label_13.setText(_translate("MainWindow", "z retraction"))
        self.labelCap_11.setText(_translate("MainWindow", "Z"))
        self.label_12.setText(_translate("MainWindow", "Lower z position"))
        self.gc_currentx_btn.setText(_translate("MainWindow", "Use Current"))
        self.gc_modefalse_rb.setText(_translate("MainWindow", "SET Sampling"))
        self.checkBox_2.setText(_translate("MainWindow", "Left to right"))
        self.label_11.setText(_translate("MainWindow", "Dwell Time"))
        self.gc_modetrue_rb.setText(_translate("MainWindow", "Conductance Sampling"))
        self.gc_currentall_btn.setText(_translate("MainWindow", "Use Current x,y,z"))
        self.gc_currentz_btn.setText(_translate("MainWindow", "Use Current"))
        self.labelCap_10.setText(_translate("MainWindow", "3.1 Sampling Path"))
        self.label_27.setText(_translate("MainWindow", "Sampling Spots"))
        self.prt_startrun_btn.setText(_translate("MainWindow", "Start Run"))
        self.label_19.setText(_translate("MainWindow", "(Pump on)"))
        self.label_22.setText(_translate("MainWindow", "(Pump off)"))
        self.label_28.setText(_translate("MainWindow", "Sampling"))
        self.label_29.setText(_translate("MainWindow", "(z down)"))
        self.label_31.setText(_translate("MainWindow", "Speed "))
        self.label_30.setText(_translate("MainWindow", "Speed"))
        self.label_32.setText(_translate("MainWindow", "z up"))
        self.label_33.setText(_translate("MainWindow", "Speed"))
        self.label_34.setText(_translate("MainWindow", "x and y"))
        self.label_35.setText(_translate("MainWindow", "z offset"))
        self.label_36.setText(_translate("MainWindow", "(up after touch)"))
        self.gc_filename_txt.setText(_translate("MainWindow", "Gcode File Name"))
        self.label_39.setText(_translate("MainWindow", "Step Distance z"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sampling Path"))
        self.labelCap_18.setText(_translate("MainWindow", "3.2 Pump Control"))
        self.pump_baud_sel.setItemText(0, _translate("MainWindow", "38400"))
        self.pump_baud_sel.setItemText(1, _translate("MainWindow", "19200"))
        self.label_17.setText(_translate("MainWindow", "Port:"))
        self.label_18.setText(_translate("MainWindow", "Baud:"))
        self.label_47.setText(_translate("MainWindow", "sample"))
        self.label_48.setText(_translate("MainWindow", "dwell"))
        self.label_86.setText(_translate("MainWindow", "resolution X"))
        self.label_87.setText(_translate("MainWindow", "resolution Y"))
        self.label_88.setText(_translate("MainWindow", "dimension X"))
        self.label_89.setText(_translate("MainWindow", "dimension Y"))
        self.label_90.setText(_translate("MainWindow", "dimensions"))
        self.resolution_mode.setText(_translate("MainWindow", "Resolution"))
        self.dimension_mode.setText(_translate("MainWindow", "Dimension"))
        
        if os.name == 'nt':
            
            selrial_ports = list(list_ports.comports())
            
            extracted_name =[ports.name for ports in serial_ports]
            extracted_ports = [ports.device for ports in serial_ports]
            self.pump_com_sel.setCurrentText(_translate("MainWindow", str(extracted_ports)))
            #go through ports and add them to the dropdown
            for count, p in enumerate(extracted_ports):
                self.pump_com_sel.setItemData(count, p)
                self.pump_com_sel.setItemText(count, _translate("MainWindow", str(extracted_name[count])))
            # self.pump_com_sel.setCurrentText(_translate("MainWindow", "COM9")) #need to make mac compatible
            # self.pump_com_sel.setItemText(0, _translate("MainWindow", "COM9"))
            # self.pump_com_sel.setItemText(1, _translate("MainWindow", "COM1"))
            # self.pump_com_sel.setItemText(2, _translate("MainWindow", "COM2"))
            # self.pump_com_sel.setItemText(3, _translate("MainWindow", "COM3"))
            # self.pump_com_sel.setItemText(4, _translate("MainWindow", "COM4"))
            # self.pump_com_sel.setItemText(5, _translate("MainWindow", "COM5"))
            # self.pump_com_sel.setItemText(6, _translate("MainWindow", "COM6"))
        else:
            # Set options for macOS
            
            serial_ports = list(list_ports.comports())
            
            
            #take off the everything after " - " in the port name
            extracted_ports = [str(port).split(' - ')[0] for port in serial_ports]
            extracted_name = [str(port).split(' - ')[1] for port in serial_ports]
            
            self.pump_com_sel.setCurrentText(_translate("MainWindow", str(extracted_ports[0])))
            #go through ports and add them to the dropdown
            for count, p in enumerate(extracted_ports):
                self.pump_com_sel.setItemData(count, p)
                self.pump_com_sel.setItemText(count, _translate("MainWindow", str(extracted_name[count])))
        
        
             
        self.pump_con_btn.setText(_translate("MainWindow", "Connect"))
        self.pump_discon_btn.setText(_translate("MainWindow", "Disconnect"))
        self.pump_setq_btn.setText(_translate("MainWindow", "Set Q"))
        self.radioButton_3.setText(_translate("MainWindow", "Constant Flow"))
        self.radioButton_4.setText(_translate("MainWindow", "Flow Program"))
        self.label_20.setText(_translate("MainWindow", "Sampling Flowrate"))
        self.label_21.setText(_translate("MainWindow", "Dwell Flowrate"))
        self.pump_start_btn.setText(_translate("MainWindow", "Start Pump"))
        self.pump_stop_btn.setText(_translate("MainWindow", "Stop Pump"))
        self.con_connect_bt_4.setText(_translate("MainWindow", "Set Syringe Diam."))
        self.label_24.setText(_translate("MainWindow", "µL / min"))
        self.label_25.setText(_translate("MainWindow", "mm"))
        self.label_26.setText(_translate("MainWindow", "mL"))
        self.con_connect_bt_5.setText(_translate("MainWindow", "Set V"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Pump Control"))
        self.prt_discon_btn.setText(_translate("MainWindow", "Disconnect"))
        self.prt_poszero_btn.setText(_translate("MainWindow", "Zero"))
        self.prt_con_btn.setText(_translate("MainWindow", "Connect"))
        self.label_23.setText(_translate("MainWindow", "M203 for feedrate"))
        self.prt_fast_btn.setText(_translate("MainWindow", "Fast"))
        self.prt_slow_btn.setText(_translate("MainWindow", "Slow"))
        self.prt_movexyval_sel.setItemText(0, _translate("MainWindow", "0.01"))
        self.prt_movexyval_sel.setItemText(1, _translate("MainWindow", "0.1"))
        self.prt_movexyval_sel.setItemText(2, _translate("MainWindow", "1"))
        self.prt_movexyval_sel.setItemText(3, _translate("MainWindow", "10"))
        self.prt_movexyval_sel.setItemText(4, _translate("MainWindow", "100"))
        self.conThread_save_btn.setText(_translate("MainWindow", "Save"))
        self.label_37.setText(_translate("MainWindow", "Scale"))
        self.label_38.setText(_translate("MainWindow", "Threshold"))
        self.label_40.setText(_translate("MainWindow", "zero at"))
        self.prt_poshundred_btn.setText(_translate("MainWindow", "Set to 100"))
        self.prt_stop_btn.setText(_translate("MainWindow", "Stop"))
        self.prt_pause_btn.setText(_translate("MainWindow", "Pause"))
        self.label_cap_16.setText(_translate("MainWindow", "6. Temperature"))
        self.label_6.setText(_translate("MainWindow", "Bed"))
        self.label_41.setText(_translate("MainWindow", "Nozzel"))
        self.labelCap_19.setText(_translate("MainWindow", "Reference"))
        self.ref_set_select.setText(_translate("MainWindow", "SET"))
        self.ref_conductance_select.setText(_translate("MainWindow", "Conductance"))
        self.label_42.setText(_translate("MainWindow", "Lower z"))
        self.label_43.setText(_translate("MainWindow", "Retract z"))
        self.label_44.setText(_translate("MainWindow", "Offset z"))
        self.label_45.setText(_translate("MainWindow", "X"))
        self.label_46.setText(_translate("MainWindow", "Y"))
        self.send_btn.setText(_translate("MainWindow", "Send"))
        self.image_btn.setText(_translate("MainWindow", "Capture"))
        self.video_btn.setText(_translate("MainWindow", "Capture Video"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
